name: Build and publish Sphinx 🪬 documentation

on:
  push:
    branches:
      - main
    paths:
      - 'weac/**'
      - 'docs/sphinx/**'

jobs:
  build-docs:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Sphinx and extensions
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinxawesome_theme

    - name: Clean old html files
      run: |
        cd docs/
        rm -rf _* *.html *.js *.inv

    - name: Generate API documentation with sphinx-apidoc
      run: |
        cd sphinx/
        sphinx-apidoc -o . ../../weac --force --separate

    - name: Build Sphinx documentation
      run: |
        make clean html

    - name: Copy built documentation to docs/
      run: |
        cp -rf _build/html/* ../../docs

    - name: Commit and push documentation
      run: |
        git add docs/
        git commit -m "Update documentation" || echo "No changes to commit"
        git push origin main
